// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';

var Pervasives = require("bs-platform/lib/js/pervasives.js");
var Json_decode = require("@glennsl/bs-json/src/Json_decode.bs.js");

((require('isomorphic-fetch')));

function getPrice(ticker) {
  return fetch("https://min-api.cryptocompare.com/data/price?fsym=" + (ticker + "&tsyms=USD")).then((function (prim) {
                      return prim.json();
                    })).then((function (json) {
                    return Promise.resolve(/* float array */[Json_decode.field("USD", Json_decode.$$float, json)]);
                  })).then((function (result) {
                  return Promise.resolve((console.log("The price of " + (ticker + (" in US Dollar is " + Pervasives.string_of_float(result[/* usd */0])))), /* () */0));
                })).catch((function () {
                return Promise.resolve((console.log("Unable to complete request"), /* () */0));
              }));
}

getPrice("BTC");

getPrice("LTC");

getPrice("ETH");

getPrice("NEO");

exports.getPrice = getPrice;
/*  Not a pure module */
